config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :pledges
  resources :categories
  resources :rewards
  resources :products
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  belongs_to :reward
 
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :set_pledge, only: [:show, :edit, :update, :destroy]

  # GET /pledges
  # GET /pledges.json
  def index
    if params[:u] == 'u'
      @pledges = Pledge.where(user_id: current_user.id)
    else
      @pledges = Pledge.all
    end
  end

  # GET /pledges/1
  # GET /pledges/1.json
  def show
  end

  # GET /pledges/new
  def new
    @pledge = Pledge.new
  end

  # GET /pledges/1/edit
  def edit
  end

  # POST /pledges
  # POST /pledges.json
  def create
    @pledge = Pledge.new(pledge_params)
    @pledge.user_id = current_user.id

    respond_to do |format|
      if @pledge.save
        format.html { redirect_to @pledge, notice: 'Pledge was successfully created.' }
        format.json { render :show, status: :created, location: @pledge }
      else
        format.html { render :new }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pledges/1
  # PATCH/PUT /pledges/1.json
  def update
    respond_to do |format|
      if @pledge.update(pledge_params)
        format.html { redirect_to @pledge, notice: 'Pledge was successfully updated.' }
        format.json { render :show, status: :ok, location: @pledge }
      else
        format.html { render :edit }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledges/1
  # DELETE /pledges/1.json
  def destroy
    @pledge.destroy
    respond_to do |format|
      format.html { redirect_to pledges_url, notice: 'Pledge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pledge
      @pledge = Pledge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pledge_params
      params.require(:pledge).permit(:user_id, :product_id, :reward_id, :amount)
    end
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/views/pledges/_form.html.erb
<%= form_tag new_pledge_path do |f| %>
<%- form_for()
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pledges/edit.html.erb
<h1>Editing Pledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @pledge %> |
<%= link_to 'Back', pledges_path %>

app/views/pledges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pledges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Reward</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pledges.each do |pledge| %>
      <tr>
        <td><%= pledge.user %></td>
        <td><%= pledge.product %></td>
        <td><%= pledge.reward %></td>
        <td><%= pledge.amount %></td>
        <td><%= link_to 'Show', pledge %></td>
        <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
        <td><%= link_to 'Destroy', pledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 

<br>

<%= link_to 'New Pledge', new_pledge_path %>

app/views/pledges/new.html.erb
<h1>New Pledge</h1>

<%= render 'form' %>

<%= link_to 'Back', pledges_path %>

app/views/pledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pledge.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @pledge.product %>
</p>

<p>
  <strong>Reward:</strong>
  <%= @pledge.reward %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @pledge.amount %>
</p>

<%= link_to 'Edit', edit_pledge_path(@pledge) %> |
<%= link_to 'Back', pledges_path %>