config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :pledges
  resources :categories
  resources :rewards
  resources :products
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag '' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>

        <!-- logo -->
        <section class="container headerLogo">
            <div class="row">
                <div class="col-md-4 text-left">
                </div>
                <div class="col-md-4 text-center">
                    <h1><a href="/">CrowdFunder</a></h1>
                </div>
                <div class="col-md-4 text-right">
                  <% if current_user %>
                    <span class="btn btn-default btn-sm btHeader"><%= link_to "Signed in as #{current_user.name}", user_path(current_user.id) %></span> |
                    <span class="btn btn-default btn-sm btHeader"><%= link_to "Log out", session_path(current_user), :method => :delete %></span>
                    <% else %>
                    <span class="btn btn-default btn-sm btHeader"><%= link_to "Log In", new_session_path %></span> |
                    <span class="btn btn-default btn-sm btHeader"><%= link_to "Sign Up", new_user_path %></span>
                    <% end %>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                </div>
            </div>
        </section>


        <!-- Menu bootstrap -->
        <nav class="navbar navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/">Projects</a></li>
                <li><a href="/">About</a></li>
                <% if current_user %>
                <li><a href="/products/new">New Campaign</a></li>
                <% end %>
                <li class="pull-right">
                    <form method="get" action="http://www.google.com" class="pull-right">
                        <input type="text" name="q" class="inputSearch" size="15" maxlength="120"><input type="submit" class="inputSearch" value="Search">
                    </form>
                </li>
              </ul>
            </div><!-- /.nav-collapse -->
          </div><!-- /.container -->
        </nav>


  </header>



<%= yield %>


<!-- Footer -->
<footer class="container-fluid">

  <div class="row">
      <div class="col-lg-12 text-center">
          <p>Copyright &copy; Crowdfunder 2016</p>
      </div>
  </div>

</footer>

</body>
</html>